import datetime
import traceback
import discord
from discord.ext import commands
from messages import *
import COC
import pickle
from discord import Embed , Color
from main import p


class rules(commands.Cog) :
    def __init__(self , client) :
        self.client = client

    @commands.command(name="fwa")
    async def rules(self , ctx) :
        await ctx.message.delete()
        image = discord.File(r"./templates/fwabanner.png" , filename="fwabanner.png")

        await ctx.send(file=image)
        message = """
        #  What is FWA?


- *The Farm War Alliance is a group of over 600+ (and climbing higher every day) clans whose primary goal is to match against each other in arranged wars.*
- *Our focus is to be able to harvest the free loot generated by the Clash system, easy stars and generous clan XP. *
- *Provided your clan’s weight, composition and start is done correctly, 96% of the time your clan will be matched with another FWA clan.*


❯ ***FWA (Farm War Alliance) consists of clans that range in weight from 3.9M to 7.2M***

# How do I recognize another FWA Clan?


- *All FWA clans MUST have their locations set to **Lesotho** and ‘ <a:fwa:1231435576637657188> ’ included in their descriptions. *
- *The <a:fwa:1231435576637657188> emoji is the official emoji of the Farm War Alliance. Also, to confirm your opponent is a valid FWA clan: *

- You can check the official Proud Clans of FWA list at 
                              - <a:fwa:1231435576637657188> [ FWA CLANS ](https://fwastats.com/Clans) <a:fwa:1231435576637657188>

- You can check the clan's association in Chocolate Clash by searching its clan tag at
     - [chocolateclash.com](https://fwa.chocolateclash.com/cc_n/)

- You can check the Members list of the FWA Leaders Band

***All FWA clans must also have their War Log set to public.***


# ***Benefits of joining a <a:fwa:1231435576637657188> FWA <a:fwa:1231435576637657188> clan:***

- *Cheap armies required*
- *Tons of loots*
- *50/50 wars*
- *Farm to max !*
- *Lazy Cwls*
- *Stress-free war*
        """
        await ctx.send(message , suppress_embeds=True)

    @commands.command(name="rules")
    async def rules(self , ctx) :
        await ctx.message.delete()
        image1 = discord.File(r"./templates/rule.png" , filename="rule.png")
        image2 = discord.File(r"./templates/do.png" , filename="rule2.png")
        image3 = discord.File(r"./templates/dont.png" , filename="rule3.png")
        await ctx.send(file=image1)
        await ctx.send(rules1)
        await ctx.send(file=image2)
        await ctx.send(rules2)
        await ctx.send(file=image3)
        await ctx.send(rules3)
        await ctx.send(lastrule)

    @commands.command(name="wi")
    async def withdraw(self , ctx) :
        await ctx.message.delete()
        await ctx.send(war1)
        image1 = discord.File(r"./templates/warinstruction.png" , filename="withdraw.png")
        await ctx.send(file=image1)
        await ctx.send(war2)
        await ctx.send(war3)
        await ctx.send(war4)
        await ctx.send(war5)





async def setup(client) :
    await client.add_cog(rules(client))
